- fail: msg="ceph_keys variable must be defined as hash"
  when: ceph_keys is not mapping 

- fail: msg="xen_sr_uuid variable must be defined to setup the XenServer Storage Repo"
  when: xen_sr_uuid is not defined or (xen_sr_uuid | trim) == ''

- name: enable base centos repos
  action: template src="CentOS.repo.j2" dest="/etc/yum.repos.d/CentOS-Base-rbdsr.repo" owner=root group=root mode=644

  