---
project_name: "ceph"


####################
# Ceph
####################

ceph_update: false
ceph_release: jewel
ceph_cluster_fsid:
ceph_mon_hosts:
# ceph_keys:
#  xenserver: <cephxkey>
# To create the cephx key, run as admin (create repo + allow access): 
#  ceph osd pool create RBD_XenStorage-<xen_sr_uuid> 512 512 replicated
#  ceph auth get-or-create client.xenserver mon 'allow r' osd 'allow rwx pool=RBD_XenStorage-<xen_sr_uuid>'
ceph_keys:

# 3.10 kernel supports only 2
#
#    layering: layering support, where id is 1
#    striping: striping v2 support, where id is 2
#    exclusive-lock: exclusive locking support, where id is 4
#    object-map: object map support (requires exclusive-lock), where id is 8
#	 fast-diff: 16
#	 deep-flatten: 32
#	 journaling: 64
# value is the total of each feature
rbd_default_features: 3
